services:
  workspace:
    environment:
      HOST: 0.0.0.0
      DANGEROUSLY_OMIT_AUTH: "true"
      MCP_AUTO_OPEN_ENABLED: "false"
    ports: !override
      - 6274:6274
      - 6277:6277
      - 8085:8085
